// apps/web/src/routes/settings/+page.svelte
<script lang="ts">
  import BottomNavigation from "$lib/components/BottomNavigation.svelte";
  import VideoLengthDial from "$lib/components/settings/VideoLengthDial.svelte";
  import BackgroundSelector from "$lib/components/settings/BackgroundSelector.svelte";
  import ToggleTile from "$lib/components/settings/ToggleTile.svelte";
  import TextScaleSlider from "$lib/components/settings/TextScaleSlider.svelte";

  import {
    videoLength,
    backgroundUrl,
    autoResume,
    darkMode,
    textScale,
  } from "$lib/stores/settings";
</script>

<svelte:head>
  <title>PaperFlip - Settings</title>
</svelte:head>

<div
  class="max-w-md mx-auto min-h-screen bg-brand-bg relative flex flex-col overflow-hidden text-foreground font-display"
>
  <!-- Background Gradients -->
  <div
    class="fixed inset-0 z-0 pointer-events-none overflow-hidden max-w-md mx-auto"
  >
    <div
      class="absolute top-0 right-0 w-64 h-64 bg-brand-primary/5 rounded-full blur-[100px] -mr-32 -mt-32"
    ></div>
    <div
      class="absolute bottom-0 left-0 w-64 h-64 bg-brand-secondary/5 rounded-full blur-[100px] -ml-32 -mb-32"
    ></div>
  </div>

  <header class="pt-12 pb-6 px-6 z-10 flex justify-between items-end">
    <div>
      <h1 class="text-3xl font-extrabold tracking-tight">Settings</h1>
      <p class="mt-1 text-brand-text-muted font-medium text-sm">
        Configure your experience
      </p>
    </div>
  </header>

  <main
    class="px-6 space-y-6 flex-grow overflow-y-auto pb-28 z-10 hide-scrollbar"
  >
    <!-- Video Length -->
    <VideoLengthDial bind:value={$videoLength} />

    <!-- Background -->
    <BackgroundSelector bind:selected={$backgroundUrl} />

    <!-- Toggles Grid -->
    <div class="grid grid-cols-2 gap-4">
      <ToggleTile
        title="Auto-Resume"
        description="Continue from last point"
        icon="play_circle"
        bind:checked={$autoResume}
      />
      <ToggleTile
        title="Dark Mode"
        description="System default"
        icon="dark_mode"
        bind:checked={$darkMode}
      />
    </div>

    <!-- Text Scale -->
    <TextScaleSlider bind:scale={$textScale} />
  </main>

  <BottomNavigation activeTab="settings" />
</div>

<style>
  /* Hide scrollbar for Chrome, Safari and Opera */
  .hide-scrollbar::-webkit-scrollbar {
    display: none;
  }

  /* Hide scrollbar for IE, Edge and Firefox */
  .hide-scrollbar {
    -ms-overflow-style: none; /* IE and Edge */
    scrollbar-width: none; /* Firefox */
  }
</style>

// apps/mobile/app/settings.tsx
import { View, Text, ScrollView } from 'react-native';
import { useEffect, useState } from 'react';
import { SafeAreaView } from 'react-native-safe-area-context';
import { VideoLengthDial } from '../src/components/settings/VideoLengthDial';
import { BackgroundSelector } from '../src/components/settings/BackgroundSelector';
import { ToggleTile } from '../src/components/settings/ToggleTile';
import { TextScaleSlider } from '../src/components/settings/TextScaleSlider';
import { getSettings, updateSettings, videoSources } from '@paperflip/core';

export default function SettingsScreen() {
  const [settings, setSettings] = useState({
    videoLength: 15,
    autoResume: true,
    darkMode: true,
    textScale: 110,
    backgroundUrl: videoSources[0].url
  });

  useEffect(() => {
    getSettings().then(s => setSettings(s)).catch(console.error);
  }, []);

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const updateSetting = (key: string, value: any) => {
    setSettings(prev => ({ ...prev, [key]: value }));
    updateSettings({ [key]: value });
  };

  return (
    <View className="flex-1 bg-brand-bg relative flex-col overflow-hidden">
      {/* Background Gradients */}
      <View className="absolute top-0 right-0 w-64 h-64 bg-brand-primary/5 rounded-full -mr-32 -mt-32" />
      <View className="absolute bottom-0 left-0 w-64 h-64 bg-brand-secondary/5 rounded-full -ml-32 -mb-32" />

      <SafeAreaView style={{flex: 1}} edges={['top']}>
        <View className="pt-12 pb-6 px-6 z-10 flex-row justify-between items-end">
          <View>
            <Text className="text-3xl font-extrabold tracking-tight text-white">Settings</Text>
            <Text className="mt-1 text-brand-text-muted font-medium text-sm">
              Configure your experience
            </Text>
          </View>
        </View>

        <ScrollView className="px-6 flex-grow z-10" contentContainerStyle={{ paddingBottom: 100, gap: 24 }}>
          {/* Video Length */}
          <VideoLengthDial
            value={settings.videoLength}
            onChange={(val) => updateSetting('videoLength', val)}
          />

          {/* Background */}
          <BackgroundSelector
            selected={settings.backgroundUrl}
            onChange={(val) => updateSetting('backgroundUrl', val)}
          />

          {/* Toggles Grid */}
          <View className="flex-row space-x-4">
            <ToggleTile
              title="Auto-Resume"
              description="Continue from last point"
              icon="play-circle"
              checked={settings.autoResume}
              onChange={(val) => updateSetting('autoResume', val)}
            />
            <ToggleTile
              title="Dark Mode"
              description="System default"
              icon="dark-mode"
              checked={settings.darkMode}
              onChange={(val) => updateSetting('darkMode', val)}
            />
          </View>

          {/* Text Scale */}
          <TextScaleSlider
            scale={settings.textScale}
            onChange={(val) => updateSetting('textScale', val)}
          />
        </ScrollView>
      </SafeAreaView>
    </View>
  );
}
