// apps/mobile/src/components/OptionsSheet.tsx
import { View, Text, Pressable, Modal } from 'react-native';
import { MaterialIcons } from '@expo/vector-icons';

type OptionsSheetProps = {
  visible: boolean;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  document: any;
  onClose: () => void;
  onDelete: (id: string) => void;
  onToggleFavourite: (id: string) => void;
};

export function OptionsSheet({ visible, document, onClose, onDelete, onToggleFavourite }: OptionsSheetProps) {
  if (!document) return null;

  const isFavourite = document.isFavourite;

  const handleToggleFavourite = () => {
    onToggleFavourite(document.documentId);
    onClose();
  };

  const handleDelete = () => {
    onDelete(document.documentId);
    onClose();
  };

  return (
    <Modal
      animationType="slide"
      transparent={true}
      visible={visible}
      onRequestClose={onClose}
    >
      <View className="flex-1 justify-end">
        {/* Backdrop */}
        <Pressable
          className="absolute inset-0 bg-black/60"
          onPress={onClose}
        />

        {/* Sheet Content */}
        <View className="bg-brand-bg/95 border-t border-white/10 rounded-t-3xl pb-10 pt-4 px-6 shadow-2xl">

          {/* Handle */}
          <View className="w-full items-center mb-6">
            <View className="w-12 h-1.5 bg-white/20 rounded-full" />
          </View>

          <View className="flex-col space-y-2">
            <Pressable
              className="flex-row items-center p-4 rounded-xl active:bg-white/10"
              onPress={handleToggleFavourite}
            >
              <View className="w-10 h-10 rounded-full bg-brand-surface-dark border border-white/10 items-center justify-center mr-4">
                <MaterialIcons
                  name={isFavourite ? "star" : "star-border"}
                  size={24}
                  color={isFavourite ? "#00FF88" : "#888"}
                />
              </View>
              <Text className="text-white font-semibold text-base">
                {isFavourite ? "Remove from Favourites" : "Set as Favourite"}
              </Text>
            </Pressable>

            <Pressable
              className="flex-row items-center p-4 rounded-xl active:bg-red-500/20 mt-2"
              onPress={handleDelete}
            >
              <View className="w-10 h-10 rounded-full bg-red-500/10 border border-red-500/20 items-center justify-center mr-4">
                <MaterialIcons name="delete" size={24} color="#EF4444" />
              </View>
              <Text className="text-red-500 font-semibold text-base">
                Delete Document
              </Text>
            </Pressable>
          </View>

        </View>
      </View>
    </Modal>
  );
}

// apps/web/src/lib/components/OptionsSheet.svelte
<script lang="ts">
  let { document, onClose, onDelete, onToggleFavourite } = $props();

  let isFavourite = $derived(document.isFavourite);

  function handleBackdropClick() {
    onClose();
  }

  function handleToggleFavourite() {
    onToggleFavourite(document.documentId);
    onClose();
  }

  function handleDelete() {
    onDelete(document.documentId);
    onClose();
  }
</script>

<div class="fixed inset-0 z-50 flex flex-col justify-end">
  <button
    type="button"
    class="absolute inset-0 bg-brand-bg/60 backdrop-blur-sm transition-opacity w-full h-full cursor-default border-none p-0 m-0"
    onclick={handleBackdropClick}
    aria-label="Close options"
    onkeydown={(e) => e.key === "Escape" && onClose()}
  ></button>
  <div
    class="relative w-full max-w-md mx-auto bg-brand-surface backdrop-blur-xl border-t border-brand-primary/10 rounded-t-3xl pb-10 pt-4 overflow-hidden shadow-2xl animate-in slide-in-from-bottom duration-300 pointer-events-auto"
  >
    <div class="w-full flex justify-center mb-6">
      <div class="w-12 h-1.5 bg-brand-text-muted/20 rounded-full"></div>
    </div>
    <div class="px-6 flex flex-col space-y-2">
      <button
        class="w-full flex items-center space-x-4 p-4 rounded-xl hover:bg-brand-primary/5 active:bg-brand-primary/10 transition-colors group text-left"
        onclick={handleToggleFavourite}
      >
        <div
          class="w-10 h-10 rounded-full bg-brand-surface-dark border border-brand-primary/10 flex items-center justify-center shrink-0"
        >
          <span
            class="material-symbols-outlined {isFavourite
              ? 'text-brand-primary'
              : 'text-brand-text-muted'} fill-1"
          >
            star
          </span>
        </div>
        <span class="text-foreground font-semibold text-base">
          {isFavourite ? "Remove from Favourites" : "Set as Favourite"}
        </span>
      </button>
      <button
        class="w-full flex items-center space-x-4 p-4 rounded-xl hover:bg-red-500/10 active:bg-red-500/20 transition-colors group"
        onclick={handleDelete}
      >
        <div
          class="w-10 h-10 rounded-full bg-red-500/10 border border-red-500/20 flex items-center justify-center shrink-0"
        >
          <span class="material-symbols-outlined text-red-500">delete</span>
        </div>
        <span class="text-red-500 font-semibold text-base">Delete Document</span
        >
      </button>
    </div>
  </div>
</div>
