// apps/mobile/src/components/settings/TextScaleSlider.tsx
import { View, Text, Pressable } from 'react-native';
import { MaterialIcons } from '@expo/vector-icons';

type TextScaleSliderProps = {
  scale: number;
  onChange: (scale: number) => void;
};

export function TextScaleSlider({ scale, onChange }: TextScaleSliderProps) {
  // Mock slider for now since pure RN doesn't have a great native slider out of the box without community
  // We'll use a simple + and - button approach or standard primitive if needed.
  // Actually, we can just build a custom pressable track or use +/- for simplicity to avoid installing new deps.

  const increment = () => onChange(Math.min(150, scale + 10));
  const decrement = () => onChange(Math.max(80, scale - 10));

  return (
    <View className="bg-brand-surface-dark/40 border border-white/5 rounded-2xl p-6">
      <View className="flex-row justify-between items-center mb-2">
        <Text className="font-bold text-lg text-white">Text Scale</Text>
        <Text className="text-xs font-mono text-brand-secondary">{scale}%</Text>
      </View>

      <View className="h-16 flex-row items-center justify-center bg-brand-surface-dark/50 rounded-lg mb-4 border border-white/5 overflow-hidden px-4">
        <Text
          style={{ fontSize: 16 * (scale / 100) }}
          className="text-white/90 leading-snug text-center"
          numberOfLines={1}
        >
          The quick brown fox jumps...
        </Text>
      </View>

      <View className="flex-row items-center space-x-3 justify-between">
        <Pressable onPress={decrement} className="p-2 bg-white/10 rounded-full">
          <MaterialIcons name="remove" size={24} color="#888" />
        </Pressable>

        <View className="flex-1 h-1 bg-white/10 mx-4 rounded-lg overflow-hidden relative">
          <View
            className="absolute left-0 top-0 bottom-0 bg-[#00FF88]"
            style={{ width: `${((scale - 80) / (150 - 80)) * 100}%` }}
          />
        </View>

        <Pressable onPress={increment} className="p-2 bg-white/10 rounded-full">
          <MaterialIcons name="add" size={24} color="#00FF88" />
        </Pressable>
      </View>
    </View>
  );
}

// apps/web/src/lib/components/settings/TextScaleSlider.svelte
<script lang="ts">
  let { scale = $bindable(110) } = $props();
</script>

<div class="glass-panel rounded-2xl p-6">
  <div class="flex justify-between items-center mb-2">
    <h3 class="font-bold text-lg text-foreground">Text Scale</h3>
    <span class="text-xs font-mono text-brand-secondary">{scale}%</span>
  </div>

  <div
    class="h-16 flex items-center justify-center bg-brand-surface-dark/50 rounded-lg mb-4 border border-brand-primary/10 overflow-hidden"
  >
    <p
      class="text-foreground/90 leading-snug text-center px-4 transition-all duration-300 whitespace-nowrap"
      style="font-size: {scale / 100}rem;"
    >
      The quick brown fox jumps over the lazy dog.
    </p>
  </div>

  <div class="flex items-center space-x-3">
    <span class="material-symbols-outlined text-brand-text-muted text-xs"
      >text_fields</span
    >
    <input
      class="w-full h-1 bg-brand-text-muted/20 rounded-lg appearance-none cursor-pointer slider-thumb"
      max="150"
      min="80"
      type="range"
      bind:value={scale}
    />
    <span class="material-symbols-outlined text-foreground text-lg"
      >text_fields</span
    >
  </div>
</div>

<style>
  .glass-panel {
    background: var(--brand-surface);
    opacity: 0.8;
    backdrop-filter: blur(12px);
    border: 1px solid var(--brand-primary);
    border-color: rgba(0, 255, 136, 0.1);
  }

  /* Slider Styling */
  input[type="range"]::-webkit-slider-thumb {
    -webkit-appearance: none;
    height: 20px;
    width: 20px;
    border-radius: 50%;
    background: #00ff88;
    cursor: pointer;
    margin-top: -8px; /* You need to specify a margin in Chrome, but in Firefox and IE it is automatic */
    box-shadow: 0 0 10px rgba(0, 255, 136, 0.5);
  }

  /* Firefox */
  input[type="range"]::-moz-range-thumb {
    height: 20px;
    width: 20px;
    border-radius: 50%;
    background: #00ff88;
    cursor: pointer;
    box-shadow: 0 0 10px rgba(0, 255, 136, 0.5);
    border: none;
  }
</style>
