// apps/mobile/app/feed.tsx
import { View, Text, ActivityIndicator } from 'react-native';
import { useEffect, useState } from 'react';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { getDb, getDocument, resegmentDocument } from '@paperflip/core';
import { Feed } from '../src/components/feed/Feed';
import { DEFAULT_SETTINGS } from '@paperflip/core';

export default function FeedScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const router = useRouter();

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const [doc, setDoc] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isResegmenting, setIsResegmenting] = useState(false);

  useEffect(() => {
    if (!id) {
      setError('No document ID provided');
      setIsLoading(false);
      return;
    }

    const loadDoc = async () => {
      try {
        await getDb(); // Ensure DB is initialized

        const loadedDoc = await getDocument(id);
        if (loadedDoc) {
          setDoc(loadedDoc);
        } else {
          setError('Document not found');
        }
      } catch (err) {
        console.error('Error loading document:', err);
        setError('Failed to load document');
      } finally {
        setIsLoading(false);
      }
    };

    loadDoc();
  }, [id]);

  useEffect(() => {
    if (doc && doc.fullText && !isResegmenting) {
      const currentVideoLength = DEFAULT_SETTINGS.videoLength; // Should get from settings store in reality
      if (doc.videoLengthAtSegmentation !== currentVideoLength) {
        console.log(`Re-segmenting document from ${doc.videoLengthAtSegmentation}s to ${currentVideoLength}s`);
        setIsResegmenting(true);
        resegmentDocument(id!, currentVideoLength)
          .then((newDoc) => {
            if (newDoc) {
              setDoc(newDoc);
            }
            setIsResegmenting(false);
          })
          .catch((e) => {
            console.error('Resegmentation failed:', e);
            setIsResegmenting(false);
          });
      }
    }
  }, [doc, id, isResegmenting]);

  if (isLoading) {
    return (
      <View className="flex-1 bg-black items-center justify-center">
        <ActivityIndicator size="large" color="#00FF88" />
        <Text className="text-white mt-4 animate-pulse">Loading feed...</Text>
      </View>
    );
  }

  if (error) {
    return (
      <View className="flex-1 bg-black items-center justify-center p-6">
        <Text className="text-red-500 text-xl text-center mb-4">{error}</Text>
        <Text className="text-[#00FF88] underline" onPress={() => router.back()}>
          Go back
        </Text>
      </View>
    );
  }

  if (doc?.segments && doc.segments.length > 0) {
    return (
      <View className="flex-1 bg-black">
        <Feed
          key={doc.videoLengthAtSegmentation} // Force remount on resegmentation
          segments={doc.segments}
          initialIndex={DEFAULT_SETTINGS.autoResume ? (doc.currentSegmentIndex || 0) : 0}
          initialProgress={DEFAULT_SETTINGS.autoResume ? (doc.currentSegmentProgress || 0) : 0}
          documentId={id!}
        />

        {isResegmenting && (
          <View className="absolute inset-0 bg-black/60 items-center justify-center z-50">
            <ActivityIndicator size="large" color="#00FF88" />
            <Text className="text-white font-bold text-lg uppercase tracking-wide mt-4">
              Resegmenting...
            </Text>
            <Text className="text-white/60 text-sm mt-2">
              Adjusting for {DEFAULT_SETTINGS.videoLength}s video length
            </Text>
          </View>
        )}
      </View>
    );
  }

  return (
    <View className="flex-1 bg-black items-center justify-center p-6">
      <Text className="text-white text-xl text-center mb-4">No content found for this document.</Text>
      <Text className="text-[#00FF88] underline" onPress={() => router.back()}>
        Go back
      </Text>
    </View>
  );
}

// src/routes/feed/+page.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { page } from "$app/stores";
  import { resolve } from "$app/paths";
  import { getDocument, getDb } from "$lib/database";
  import Feed from "$lib/components/Feed.svelte";

  let segmentedData: string[] = $state([]);
  let startSegmentIndex: number = $state(0);
  let startSegmentProgress: number = $state(0);
  let currentDocumentId: string = $state("");
  let isLoading: boolean = $state(true);
  let error: string | null = $state(null);

  onMount(async () => {
    const documentId = $page.url.searchParams.get("id");
    if (!documentId) {
      error = "No document ID provided";
      isLoading = false;
      return;
    }
    currentDocumentId = documentId;

    try {
      await getDb(); // Ensure DB is initialized
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const doc: any = await getDocument(documentId);
      if (doc) {
        segmentedData = doc.segments;
        startSegmentIndex = doc.currentSegmentIndex || 0;
        startSegmentProgress = doc.currentSegmentProgress || 0;
      } else {
        error = "Document not found";
      }
    } catch (e) {
      console.error("Error loading document:", e);
      error = "Failed to load document";
    } finally {
      isLoading = false;
    }
  });
</script>

<div
  class="h-screen w-full bg-brand-bg flex justify-center items-center overflow-hidden"
>
  <div class="h-full aspect-[9/16] max-w-full bg-black shadow-2xl relative">
    {#if isLoading}
      <div class="flex items-center justify-center h-full">
        <p class="text-white text-xl animate-pulse">Loading feed...</p>
      </div>
    {:else if error}
      <div
        class="flex flex-col items-center justify-center h-full text-center p-6"
      >
        <p class="text-xl text-red-500 mb-4">{error}</p>
        <a href={resolve("/")} class="text-brand-primary underline">Go back</a>
      </div>
    {:else if segmentedData.length > 0}
      <Feed
        segments={segmentedData}
        initialIndex={startSegmentIndex}
        initialProgress={startSegmentProgress}
        documentId={currentDocumentId}
      />
    {:else}
      <div
        class="flex flex-col items-center justify-center h-full text-center p-6"
      >
        <p class="text-white text-xl mb-4">
          No content found for this document.
        </p>
        <a href={resolve("/")} class="text-brand-primary underline">Go back</a>
      </div>
    {/if}
  </div>
</div>
