// apps/mobile/src/components/DocumentGridItem.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
import { View, Text, Pressable, Image } from 'react-native';
import { MaterialIcons } from '@expo/vector-icons';
import { Link } from 'expo-router';
import { useMemo } from 'react';

type DocumentProps = {
  document: any;
  onShowOptions?: (document: any) => void;
};

export function DocumentGridItem({ document, onShowOptions }: DocumentProps) {
  const progress = useMemo(() => {
    const totalSegments = document.totalSegments ?? (document.segments?.length || 0);
    if (totalSegments === 0) return 0;

    const currentIdx = document.currentSegmentIndex || 0;
    const currentProgress = document.currentSegmentProgress || 0;
    const currentSegmentLength = document.currentSegmentLength ?? (document.segments?.[currentIdx]?.length || 1);

    const segmentPercentage = currentProgress / (currentSegmentLength || 1);
    return Math.min(100, Math.round(((currentIdx + segmentPercentage) / totalSegments) * 100));
  }, [document]);

  const icons = ['science', 'history-edu', 'psychology', 'code', 'article', 'menu-book'] as const;
  const colors = [
    { text: 'text-brand-primary', bg: 'bg-brand-primary' },
    { text: 'text-brand-secondary', bg: 'bg-brand-secondary' },
    { text: 'text-purple-400', bg: 'bg-purple-400' },
    { text: 'text-yellow-400', bg: 'bg-yellow-400' },
    { text: 'text-pink-400', bg: 'bg-pink-400' },
  ];

  const hash = useMemo(() => {
    return document.documentId.split('').reduce((acc: number, char: string) => acc + char.charCodeAt(0), 0);
  }, [document.documentId]);

  const iconName = icons[hash % icons.length];
  const colorObj = colors[hash % colors.length];

  return (
    <View className="bg-brand-surface border border-brand-primary/10 rounded-xl overflow-hidden flex-col h-48 mb-4 w-[48%] relative">
      <Link href={`/feed?id=${encodeURIComponent(document.documentId)}`} asChild>
        <Pressable className="flex-col h-full w-full">
          <View className="h-24 bg-brand-surface-dark relative items-center justify-center overflow-hidden">
            {document.thumbnailUri ? (
              <Image source={{ uri: document.thumbnailUri }} style={{ width: '100%', height: '100%' }} resizeMode="cover" />
            ) : (
              <MaterialIcons name={iconName} size={40} className={`${colorObj.text} opacity-40`} color="white" />
            )}
            <View className="absolute inset-0 bg-black/20 opacity-0" />
          </View>

          <View className="p-2 flex-grow flex-col justify-between">
            <View>
              <Text className="font-bold text-xs text-white leading-tight mb-1" numberOfLines={1}>
                {document.documentId}
              </Text>
              <Text className="text-[9px] text-brand-text-muted" numberOfLines={1}>
                {document.totalSegments ?? (document.segments?.length || 0)} Segments • PDF
              </Text>
            </View>
            <View className="mt-2">
              <View className="w-full bg-white/5 rounded-full h-1 overflow-hidden">
                <View className="bg-brand-primary h-full rounded-full" style={{ width: `${progress}%` }} />
              </View>
            </View>
          </View>
        </Pressable>
      </Link>

      <Pressable
        testID="more-options-button"
        className="absolute top-1 right-1 p-2 rounded-full z-20"
        onPress={(e) => {
          e.stopPropagation();
          onShowOptions?.(document);
        }}
      >
        <MaterialIcons name="more-vert" size={20} color="rgba(255,255,255,0.5)" />
      </Pressable>
    </View>
  );
}

// src/lib/components/DocumentGridItem.svelte
<script lang="ts">
  import { resolve } from "$app/paths";

  let { document, onShowOptions } = $props();

  const progress = $derived.by(() => {
    const totalSegments = document.segments?.length || 0;
    if (totalSegments === 0) return 0;

    const currentIdx = document.currentSegmentIndex || 0;
    const currentProgress = document.currentSegmentProgress || 0;
    const currentSegmentLength = document.segments[currentIdx]?.length || 1;

    // Calculate percentage within current segment
    const segmentPercentage = currentProgress / currentSegmentLength;

    // Calculate total percentage
    return Math.min(
      100,
      Math.round(((currentIdx + segmentPercentage) / totalSegments) * 100),
    );
  });

  const icons = [
    "science",
    "history_edu",
    "psychology",
    "code",
    "article",
    "menu_book",
  ];
  const colors = [
    { text: "text-brand-primary", bg: "bg-brand-primary" },
    { text: "text-brand-secondary", bg: "bg-brand-secondary" },
    { text: "text-purple-400", bg: "bg-purple-400" },
    { text: "text-yellow-400", bg: "bg-yellow-400" },
    { text: "text-pink-400", bg: "bg-pink-400" },
  ];

  const hash = $derived(
    document.documentId
      .split("")
      .reduce((acc: number, char: string) => acc + char.charCodeAt(0), 0),
  );
  const icon = $derived(icons[hash % icons.length]);
  const colorObj = $derived(colors[hash % colors.length]);
</script>

<div
  class="bg-brand-surface border border-white/5 rounded-xl overflow-hidden flex flex-col h-full hover:border-white/10 transition-colors group relative"
>
  <a
    href="{resolve('/feed')}?id={encodeURIComponent(document.documentId)}"
    class="flex flex-col h-full w-full"
  >
    <div class="h-24 bg-brand-surface-dark relative">
      <div
        class="w-full h-full bg-gradient-to-br from-brand-surface-dark to-[#050510] flex items-center justify-center"
      >
        <span
          class="material-symbols-outlined {colorObj.text} opacity-40 text-4xl"
        >
          {icon}
        </span>
      </div>
      <div
        class="absolute inset-0 flex items-center justify-center bg-black/20 opacity-0 group-hover:opacity-100 transition-opacity"
      >
        <div
          class="w-8 h-8 rounded-full bg-brand-primary/20 backdrop-blur flex items-center justify-center border border-brand-primary/50"
        >
          <span
            class="material-symbols-outlined text-brand-primary text-base fill-1"
            >play_arrow</span
          >
        </div>
      </div>
    </div>

    <div class="p-2 flex-grow flex flex-col justify-between">
      <div>
        <h4 class="font-bold text-xs text-white leading-tight truncate mb-1">
          {document.documentId}
        </h4>
        <p class="text-[9px] text-brand-text-muted truncate">
          {document.segments?.length || 0} Segments • PDF
        </p>
      </div>
      <div class="mt-2">
        <div class="w-full bg-white/5 rounded-full h-0.5 overflow-hidden">
          <div
            class="{colorObj.bg} h-full rounded-full shadow-[0_0_8px_rgba(0,255,136,0.6)]"
            style="width: {progress}%"
          ></div>
        </div>
      </div>
    </div>
  </a>

  <button
    class="absolute top-1 right-1 p-2 rounded-full text-white/50 hover:text-white hover:bg-black/20 z-20 transition-all"
    onclick={(e) => {
      e.preventDefault();
      e.stopPropagation();
      onShowOptions?.(document);
    }}
    aria-label="More options"
  >
    <span class="material-symbols-outlined text-lg">more_vert</span>
  </button>
</div>
