// apps/mobile/src/components/feed/FeedSlide.tsx
import React, { useMemo, useEffect } from 'react';
import { View, Text, Dimensions } from 'react-native';
import { useVideoPlayer, VideoView } from 'expo-video';
import { splitSentences } from '@paperflip/core';
import { LinearGradient } from 'expo-linear-gradient';

const { width, height } = Dimensions.get('window');

interface FeedSlideProps {
  segment: string;
  isActive: boolean;
  isPlaying: boolean;
  currentCharIndex: number;
  highlightEndIndex?: number;
  highlightStartIndex?: number;
  videoSource: string;
  textScale?: number;
  isMuted?: boolean;
}

export function FeedSlide({
  segment = '',
  isActive,
  isPlaying = true,
  currentCharIndex,
  highlightEndIndex,
  highlightStartIndex,
  videoSource,
  textScale = 100,
  isMuted = true,
}: FeedSlideProps) {
  const player = useVideoPlayer(videoSource, (p) => {
    p.loop = true;
    p.muted = isMuted;
    if (isActive && isPlaying) {
      p.play();
    }
  });

  useEffect(() => {
    if (isActive && isPlaying) {
      player.play();
    } else {
      player.pause();
    }
  }, [player, isActive, isPlaying]);

  useEffect(() => {
    player.muted = isMuted;
  }, [player, isMuted]);

  const words = useMemo(() => {
    if (!segment) return [];
    const w: { word: string; start: number; end: number }[] = [];
    const wordRegex = /\S+/g;
    let match;
    while ((match = wordRegex.exec(segment)) !== null) {
      w.push({
        word: match[0],
        start: match.index,
        end: match.index + match[0].length,
      });
    }
    return w;
  }, [segment]);

  const sentences = useMemo(() => {
    if (!segment) return [];
    return splitSentences(segment);
  }, [segment]);

  const currentSentence = useMemo(() => {
    if (currentCharIndex === -1 || !isActive) {
      return sentences.length > 0 ? sentences[0] : null;
    }
    const found = sentences.find(
      (s) => currentCharIndex >= s.start && currentCharIndex < s.end
    );
    if (found) return found;

    if (sentences.length === 0) return null;
    if (currentCharIndex < sentences[0].start) return sentences[0];
    if (currentCharIndex >= sentences[sentences.length - 1].end)
      return sentences[sentences.length - 1];

    let prev;
    for (let i = sentences.length - 1; i >= 0; i--) {
      if (sentences[i].start <= currentCharIndex) {
        prev = sentences[i];
        break;
      }
    }
    return prev || sentences[0];
  }, [sentences, currentCharIndex, isActive]);

  const visibleWords = useMemo(() => {
    const result = [];
    if (highlightEndIndex !== undefined) {
      const startIndex = highlightStartIndex ?? currentCharIndex;
      for (let i = 0; i < words.length; i++) {
        const w = words[i];
        if (w.start >= startIndex && w.end <= highlightEndIndex) {
          result.push(w);
        }
      }
    } else {
      if (!currentSentence) return words;
      for (let i = 0; i < words.length; i++) {
        const w = words[i];
        if (w.start >= currentSentence.start && w.end <= currentSentence.end) {
          result.push(w);
        }
      }
    }
    return result;
  }, [words, highlightEndIndex, highlightStartIndex, currentCharIndex, currentSentence]);

  // Progress based on character index for smoother animation
  const progress = useMemo(() => {
    return segment.length > 0
      ? Math.min(100, (Math.max(0, currentCharIndex) / segment.length) * 100)
      : 0;
  }, [segment, currentCharIndex]);

  const renderWord = (w: typeof words[0], index: number) => {
    const isDictation = highlightEndIndex !== undefined;
    const active = isDictation
      ? w.start >= currentCharIndex && w.end <= (highlightEndIndex ?? 0)
      : currentCharIndex >= w.start && currentCharIndex < w.end;
    const past = w.end <= currentCharIndex;

    let textColorClass = 'text-white/50';
    if (active) {
      textColorClass = 'text-[#00FF88] font-bold'; // text-brand-primary equivalent
    } else if (past) {
      textColorClass = 'text-white/80';
    }

    // Applying scale style via inline styles as NativeWind arbitrary classes might be tricky in text.
    // However, tailwind supports `text-white/50` generally. Let's use standard className text coloring and inline styles for transforms.

    return (
      <Text
        key={`${w.start}-${index}`}
        className={`inline-block text-center ${textColorClass} ${active ? 'mx-1.5' : 'mx-[2px]'}`}
        style={{
          fontSize: (textScale / 100) * 24, // Base size ~24px
          lineHeight: (textScale / 100) * 36,
          textShadowColor: active ? '#00FF88' : 'transparent',
          textShadowOffset: { width: 0, height: 0 },
          textShadowRadius: active ? 12 : 0,
          transform: [{ scale: active ? 1.1 : 1 }],
        }}
      >
        {w.word}{' '}
      </Text>
    );
  };

  return (
    <View className="flex-1 bg-black relative overflow-hidden" style={{ width, height }}>
      <View className="absolute inset-0 z-0">
        <VideoView
          player={player}
          className="w-full h-full opacity-80"
          contentFit="cover"
          nativeControls={false}
        />
        {/* Gradient Overlay */}
        <LinearGradient
          colors={['rgba(88, 28, 135, 0.4)', 'rgba(30, 58, 138, 0.4)', 'rgba(19, 78, 74, 0.4)']}
          start={{ x: 0, y: 0 }}
          end={{ x: 1, y: 1 }}
          className="absolute inset-0"
        />
      </View>

      <View className="relative z-10 flex-1 flex-col justify-center px-8 py-20 pointer-events-none">
        <View className="bg-black/60 rounded-2xl px-6 py-8 border border-white/10 shadow-xl max-w-[90%] mx-auto overflow-hidden">
            {/* Blur backdrop is tricky without expo-blur, using a solid transparent color instead for RN compatibility */}
          <Text
            className="text-center font-medium leading-relaxed"
            style={{ fontSize: (textScale / 100) * 24 }}
          >
            {visibleWords.map((w, i) => renderWord(w, i))}
          </Text>
        </View>
      </View>

      {/* Progress Bar (simplified for mobile without scrubbing for now, matching simple playback progress) */}
      <View className="absolute bottom-0 left-0 right-0 z-30 h-2 flex items-end">
        <View className="w-full h-1 bg-white/10">
          <View
            className="h-full bg-[#00FF88]"
            style={{ width: `${progress}%` }}
          />
        </View>
      </View>
    </View>
  );
}

// src/lib/components/FeedSlide.svelte
<script lang="ts">
  import { Volume2, VolumeX, ChevronUp } from "lucide-svelte";
  import { scale } from "svelte/transition";

  export let segment: string;
  export let index: number;
  export let isActive: boolean;
  export let isPlaying: boolean = true;
  export let currentCharIndex: number;
  export let highlightEndIndex: number | undefined = undefined;
  export let videoSource: string;
  import { videoAssetUrls } from "$lib/stores/assets";
  import { wordCount } from "$lib/constants";
  import { isMuted } from "$lib/stores/audio";

  let videoEl: HTMLVideoElement;
  let words: { word: string; start: number; end: number }[] = [];
  let currentWordIdx = -1;

  $: cachedSource = $videoAssetUrls[videoSource] || videoSource;

  $: if (videoEl) {
    if (isActive && isPlaying) {
      videoEl.play().catch(() => {});
    } else {
      videoEl.pause();
    }
  }

  $: {
    if (segment) {
      words = [];
      const wordRegex = /\S+/g;
      let match;
      while ((match = wordRegex.exec(segment)) !== null) {
        words.push({
          word: match[0],
          start: match.index,
          end: match.index + match[0].length,
        });
      }
    }
  }

  $: {
    if (currentCharIndex === -1 || !isActive) {
      currentWordIdx = -1;
    } else {
      // Find current word index based on char index
      currentWordIdx = words.findIndex(
        (w) => currentCharIndex >= w.start && currentCharIndex < w.end,
      );
      if (currentWordIdx === -1) {
        // Fallback: find the closest word that started before charIndex
        currentWordIdx = words.findIndex((w) => currentCharIndex < w.start) - 1;
        // If still -1 (before first word) or wasn't found (end of text?), handle edges
        if (currentWordIdx < -1) currentWordIdx = words.length - 1;
        if (currentWordIdx === -2) currentWordIdx = -1; // Before first word
      }
    }
  }

  // Progress based on word index
  $: progress =
    words.length > 0 ? ((currentWordIdx + 1) / words.length) * 100 : 0;

  $: startIndex =
    currentWordIdx === -1
      ? 0
      : Math.floor(currentWordIdx / wordCount) * wordCount;

  // In dictation mode, we want to show all words in the current sentence (range).
  // If highlightEndIndex is set, find all words within [currentCharIndex, highlightEndIndex].
  $: visibleWords =
    highlightEndIndex !== undefined
      ? words.filter(
          (w) => w.start >= currentCharIndex && w.end <= highlightEndIndex,
        )
      : words.slice(startIndex, startIndex + wordCount);

  function toggleMute(e: MouseEvent) {
    e.stopPropagation();
    isMuted.update((v) => !v);
  }
</script>

<div class="w-full h-full relative overflow-hidden bg-black">
  <!-- Video Background Layer -->
  <div class="absolute inset-0 z-0">
    <video
      bind:this={videoEl}
      class="w-full h-full object-cover opacity-80"
      src={cachedSource}
      loop
      muted={$isMuted}
      playsinline
    ></video>
    <!-- Gradient Overlay -->
    <div
      class="absolute inset-0 bg-gradient-to-br from-purple-900/40 via-blue-900/40 to-teal-900/40 mix-blend-overlay"
    ></div>
  </div>

  <!-- Floating TTS Indicator (Top Right) -->
  {#if isActive && currentWordIdx > -1}
    <button
      transition:scale
      class="absolute top-8 right-8 z-20 w-14 h-14 rounded-full bg-gradient-to-br from-brand-primary to-brand-secondary flex items-center justify-center shadow-lg shadow-brand-primary/30 animate-pulse hover:scale-110 transition-transform active:scale-95"
      on:click={toggleMute}
      aria-label={$isMuted ? "Unmute" : "Mute"}
    >
      {#if $isMuted}
        <VolumeX class="w-6 h-6 text-black" />
      {:else}
        <Volume2 class="w-6 h-6 text-black" />
      {/if}
    </button>
  {/if}

  <!-- Glassmorphism Text Container -->
  <div
    class="relative z-10 h-full flex flex-col justify-center px-8 py-20 pointer-events-none"
  >
    <div
      class="backdrop-blur-xl bg-black/60 rounded-2xl px-6 py-8 border border-white/10 shadow-xl max-w-[90%] mx-auto"
    >
      <div class="text-base leading-relaxed text-center font-medium">
        {#each visibleWords as w, i (startIndex + i)}
          {@const globalIdx = startIndex + i}
          {@const isDictation = highlightEndIndex !== undefined}
          {@const active = isDictation
            ? w.start >= currentCharIndex && w.end <= (highlightEndIndex ?? 0)
            : globalIdx === currentWordIdx}
          {@const past = w.end <= currentCharIndex}
          <span
            class="inline-block transition-all duration-200 {active ? 'mx-1.5' : 'mx-[2px]'} {active
              ? 'text-brand-primary font-bold scale-110 drop-shadow-[0_0_12px_var(--brand-primary)]'
              : past
                ? 'text-white/80'
                : 'text-white/50'}"
          >
            {w.word}
          </span>
        {/each}
      </div>
    </div>

    <!-- Swipe Up Hint (only on first slide when active) -->
    {#if index === 0 && isActive}
      <div
        class="absolute bottom-40 left-1/2 -translate-x-1/2 flex flex-col items-center gap-2 opacity-80 animate-bounce z-30"
      >
        <ChevronUp class="w-10 h-10 text-brand-primary" />
        <p class="text-white text-sm font-bold drop-shadow-lg">
          Swipe up to continue
        </p>
      </div>
    {/if}
  </div>

  <!-- Progress Bar -->
  <div class="absolute bottom-0 left-0 right-0 z-20">
    <div class="h-1 bg-white/10">
      <div
        class="h-full bg-gradient-to-r from-brand-primary to-brand-secondary transition-all duration-300 ease-out"
        style="width: {progress}%"
      ></div>
    </div>
  </div>
</div>
