// apps/mobile/src/components/feed/Feed.tsx
import React, { useState, useEffect, useRef, useCallback } from 'react';
import { View, Text, Pressable, Dimensions } from 'react-native';
import PagerView from 'react-native-pager-view';
import * as Speech from 'expo-speech';
import { Feather } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { splitSentences } from '@paperflip/core';
import { videoSources } from '@paperflip/core';
import { updateDocumentProgress, DEFAULT_SETTINGS } from '@paperflip/core';
import { FeedSlide } from './FeedSlide';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ReadingOptionsSheet } from '../ReadingOptionsSheet';

const { width, height } = Dimensions.get('window');

interface FeedProps {
  segments: string[];
  initialIndex?: number;
  initialProgress?: number;
  documentId: string;
}

export function Feed({
  segments = [],
  initialIndex = 0,
  initialProgress = 0,
  documentId,
}: FeedProps) {
  const router = useRouter();
  const pagerRef = useRef<PagerView>(null);

  const [activeIndex, setActiveIndex] = useState(initialIndex);
  const [currentCharIndex, setCurrentCharIndex] = useState(-1);
  const [highlightEndIndex, setHighlightEndIndex] = useState<number | undefined>(undefined);
  const [highlightStartIndex, setHighlightStartIndex] = useState<number | undefined>(undefined);
  const [isPlaying, setIsPlaying] = useState(false);
  const [isPausedState, setIsPausedState] = useState(false);
  const [isMuted, setIsMuted] = useState(true);
  const [backgroundUrlIndex, setBackgroundUrlIndex] = useState(0);

  const [isDictationMode, setIsDictationMode] = useState(false);

  const [optionsVisible, setOptionsVisible] = useState(false);
  const [playbackRate, setPlaybackRate] = useState(1.0);
  const [autoScroll, setAutoScroll] = useState(false);

  // Ref for mutable state that doesn't need to trigger re-renders but is accessed in callbacks
  const stateRef = useRef({
    currentCharIndex: -1,
    currentSegmentProgress: 0,
    isPlaying: false,
    boundaryFired: false,
  });

  const saveTimeout = useRef<ReturnType<typeof setTimeout> | null>(null);
  const boundaryCheckTimeout = useRef<ReturnType<typeof setTimeout> | null>(null);

  const saveProgress = useCallback((immediate = false) => {
    if (!documentId) return;
    if (saveTimeout.current) clearTimeout(saveTimeout.current);

    if (immediate) {
      updateDocumentProgress(documentId, activeIndex, stateRef.current.currentSegmentProgress);
    } else {
      saveTimeout.current = (setTimeout(() => {
        updateDocumentProgress(documentId, activeIndex, stateRef.current.currentSegmentProgress);
      }, 1000) as unknown as ReturnType<typeof setTimeout>);
    }
  }, [documentId, activeIndex]);

  const stopTTS = useCallback(async () => {
    await Speech.stop();
    stateRef.current.isPlaying = false;
    setIsPlaying(false);
  }, []);

  const speakKaraoke = useCallback(async (text: string, startIndex: number) => {
    stateRef.current.boundaryFired = false;
    stateRef.current.isPlaying = true;
    setIsPlaying(true);

    const voiceOptions: Speech.SpeechOptions = {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      onBoundary: (event: any) => {
        if (!event || event.charIndex === undefined) return; // Sometimes undefined depending on platform
        stateRef.current.boundaryFired = true;
        if (boundaryCheckTimeout.current) clearTimeout(boundaryCheckTimeout.current);
        const newIndex = event.charIndex + startIndex; // Adjust if using offset (not supported on all platforms natively with offset)
        setCurrentCharIndex(newIndex);
        stateRef.current.currentSegmentProgress = newIndex;
        stateRef.current.currentCharIndex = newIndex;
      },
      onDone: () => {
        if (boundaryCheckTimeout.current) clearTimeout(boundaryCheckTimeout.current);
        setIsPlaying(false);
        stateRef.current.isPlaying = false;
        setCurrentCharIndex(text.length);
        stateRef.current.currentSegmentProgress = text.length;
        setHighlightEndIndex(undefined);
        setHighlightStartIndex(undefined);
        saveProgress(true);
      },
      onStopped: () => {
        // Handled by explicit stops
      },
      onError: () => {
        setIsPlaying(false);
        stateRef.current.isPlaying = false;
      },
      rate: playbackRate
    };

    // React Native Expo Speech boundary events are notoriously unreliable across Android/iOS.
    // We add a boundary check fallback similar to web, forcing Dictation mode if not working.
    boundaryCheckTimeout.current = setTimeout(() => {
      if (!stateRef.current.boundaryFired && stateRef.current.isPlaying) {
        console.warn("Boundary events missing or slow, switching to Dictation Mode");
        stopTTS().then(() => {
          setIsDictationMode(true);
          // We can't immediately restart here easily without complex state management in RN
          // This relies on user interaction or the next slide to kick in properly,
          // but for simplicity in parity, we set the mode.
        });
      }
    }, 2500);

    // If there's an offset, some platforms don't support it natively for TTS.
    // For true parity we might need to substring the text if offset > 0.
    const textToSpeak = startIndex > 0 ? text.substring(startIndex) : text;
    Speech.speak(textToSpeak, voiceOptions);

  }, [saveProgress, stopTTS]);

  const speakDictation = useCallback(async (text: string, startIndex: number) => {
    const sentences = splitSentences(text);
    const sentenceQueue = sentences.filter((s) => s.end > startIndex);

    const playNextSentence = async (queue: typeof sentences, originalStartIndex: number) => {
      if (queue.length === 0 || !stateRef.current.isPlaying) {
        setIsPlaying(false);
        stateRef.current.isPlaying = false;
        if (segments[activeIndex]) {
          setCurrentCharIndex(segments[activeIndex].length);
          stateRef.current.currentSegmentProgress = segments[activeIndex].length;
        }
        setHighlightEndIndex(undefined);
        setHighlightStartIndex(undefined);
        saveProgress(true);
        return;
      }

      const currentSentence = queue[0];
      const remaining = queue.slice(1);

      setCurrentCharIndex(currentSentence.start);
      setHighlightEndIndex(currentSentence.end);
      setHighlightStartIndex(currentSentence.start);
      stateRef.current.currentSegmentProgress = currentSentence.start;

      const offset = Math.max(0, originalStartIndex - currentSentence.start);
      const textToSpeak = offset > 0 ? currentSentence.text.substring(offset) : currentSentence.text;

      Speech.speak(textToSpeak, {
        onDone: () => {
          if (!stateRef.current.isPlaying) return;
          playNextSentence(remaining, 0);
        },
        onError: () => {
          setIsPlaying(false);
          stateRef.current.isPlaying = false;
        },
        rate: playbackRate
      });
    };

    stateRef.current.isPlaying = true;
    setIsPlaying(true);
    playNextSentence(sentenceQueue, startIndex);

  }, [segments, activeIndex, saveProgress]);


  const speakCurrentSlide = useCallback(async (overrideStartIndex?: number) => {
    await stopTTS();
    if (boundaryCheckTimeout.current) clearTimeout(boundaryCheckTimeout.current);

    setCurrentCharIndex(-1);
    setHighlightEndIndex(undefined);
    setHighlightStartIndex(undefined);

    let startIndex = overrideStartIndex ?? 0;

    // For initial load
    if (overrideStartIndex === undefined && activeIndex === initialIndex && initialProgress > 0) {
      // In a real implementation we'd check if it's the first play,
      // here we simplify to starting at the initialProgress if we're on the initial slide.
      startIndex = initialProgress;
    }

    setCurrentCharIndex(startIndex);
    stateRef.current.currentSegmentProgress = startIndex;
    stateRef.current.currentCharIndex = startIndex;

    const currentSegment = segments[activeIndex];
    if (!currentSegment) return;

    // Use current state settings
    const modeDictation = isDictationMode || !DEFAULT_SETTINGS.karaokeMode;

    if (modeDictation) {
      await speakDictation(currentSegment, startIndex);
    } else {
      await speakKaraoke(currentSegment, startIndex);
    }
  }, [activeIndex, initialIndex, initialProgress, segments, isDictationMode, speakDictation, speakKaraoke, stopTTS]);


  useEffect(() => {
    // Component mount
    if (segments.length > 0) {
      // Small delay to ensure PagerView has settled if not on index 0
      setTimeout(() => {
         speakCurrentSlide();
      }, 500);
    }

    return () => {
      stopTTS();
      if (boundaryCheckTimeout.current) clearTimeout(boundaryCheckTimeout.current);
      if (saveTimeout.current) clearTimeout(saveTimeout.current);
      saveProgress(true);
    };
  }, [activeIndex, segments.length]); // Intentionally omitting speakCurrentSlide to avoid re-triggering on its deps

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const handlePageSelected = (e: any) => {
    const newIndex = e.nativeEvent.position;
    if (newIndex !== activeIndex) {
      setActiveIndex(newIndex);
      stateRef.current.currentSegmentProgress = 0;
      saveProgress();
    }
  };

  const togglePlayback = async () => {
    if (isPlaying) {
      await Speech.pause();
      setIsPlaying(false);
      setIsPausedState(true);
      stateRef.current.isPlaying = false;
      saveProgress(true);
    } else {
      if (isPausedState) {
        await Speech.resume();
        setIsPlaying(true);
        setIsPausedState(false);
        stateRef.current.isPlaying = true;
      } else {
        await speakCurrentSlide(stateRef.current.currentSegmentProgress);
      }
    }
  };

  const handleDoubleClick = () => {
    setBackgroundUrlIndex((prev) => (prev + 1) % videoSources.length);
  };

  let lastTap: number | null = null;
  const handleTap = () => {
    const now = Date.now();
    const DOUBLE_PRESS_DELAY = 300;
    if (lastTap && (now - lastTap) < DOUBLE_PRESS_DELAY) {
      handleDoubleClick();
    } else {
      togglePlayback();
    }
    lastTap = now;
  };

  if (segments.length === 0) {
    return (
      <View className="flex-1 bg-black items-center justify-center">
        <Text className="text-white text-xl">Upload a PDF to see the feed!</Text>
      </View>
    );
  }

  return (
    <View className="flex-1 bg-black relative">
      <SafeAreaView style={{position: 'absolute', top: 0, left: 0, right: 0, zIndex: 40}} edges={['top']}>
        <View className="p-4 flex-row items-center justify-between pointer-events-none">
          <Pressable
            testID="back-button"
            onPress={() => { stopTTS(); router.back(); }}
            className="w-12 h-12 rounded-full items-center justify-center bg-black/40 border border-white/15 pointer-events-auto"
          >
            <Feather name="chevron-left" size={24} color="white" />
          </Pressable>

          <View className="px-4 py-2 rounded-full bg-black/40 border border-white/15">
            <Text className="text-sm font-medium text-white/90">
              Short {activeIndex + 1} / {segments.length}
            </Text>
          </View>

          <Pressable
            onPress={() => setOptionsVisible(true)}
            className="w-12 h-12 rounded-full items-center justify-center bg-black/40 border border-white/15 pointer-events-auto"
          >
            <Feather name="more-horizontal" size={24} color="white" />
          </Pressable>
        </View>
      </SafeAreaView>

      <Pressable className="flex-1" onPress={handleTap}>
        <PagerView
          ref={pagerRef}
          style={{ flex: 1, width, height }}
          initialPage={initialIndex}
          orientation="vertical"
          onPageSelected={handlePageSelected}
          overdrag={true}
        >
          {segments.map((segment, i) => {
            // Memory optimization: render only current, previous, and next slides
            const isNearActive = Math.abs(i - activeIndex) <= 1;

            if (!isNearActive) {
               return (
                 <View key={i} style={{ flex: 1, width, height, backgroundColor: 'black' }} />
               );
            }

            return (
              <View key={i} style={{ flex: 1, width, height }}>
                <FeedSlide
                  segment={segment}
                  isActive={i === activeIndex}
                  isPlaying={isPlaying}
                  currentCharIndex={i === activeIndex ? currentCharIndex : -1}
                  highlightEndIndex={i === activeIndex ? highlightEndIndex : undefined}
                  highlightStartIndex={i === activeIndex ? highlightStartIndex : undefined}
                  videoSource={videoSources[(backgroundUrlIndex + i) % videoSources.length].url}
                  isMuted={isMuted}
                />
              </View>
            );
          })}
        </PagerView>
      </Pressable>

      {/* Footer / Controls */}
      <View className="absolute bottom-10 left-0 w-full z-40 p-4 pointer-events-none flex-col items-center">
        <View className="w-full flex-row justify-start pb-4 pl-4 pointer-events-auto">
          <Pressable
            className="w-10 h-10 rounded-full items-center justify-center shadow-lg bg-[#00FF88]"
            onPress={() => setIsMuted(!isMuted)}
          >
            {isMuted ? (
              <Feather name="volume-x" size={20} color="black" />
            ) : (
              <Feather name="volume-2" size={20} color="black" />
            )}
          </Pressable>
        </View>

        {activeIndex === 0 && (
          <View className="items-center mb-8">
            <Feather name="chevron-up" size={32} color="#00FF66" className="animate-bounce" />
            <Text className="text-xs font-medium text-white/90 tracking-wide uppercase mt-1">
              Swipe up to continue
            </Text>
          </View>
        )}
      </View>

      <ReadingOptionsSheet
        visible={optionsVisible}
        onClose={() => setOptionsVisible(false)}
        playbackRate={playbackRate}
        onPlaybackRateChange={setPlaybackRate}
        autoScroll={autoScroll}
        onAutoScrollToggle={() => setAutoScroll(!autoScroll)}
      />
    </View>
  );
}

// src/lib/components/Feed.svelte
<script lang="ts">
  import { onMount, onDestroy, untrack } from "svelte";
  import { register } from "swiper/element/bundle";
  import { resolve } from "$app/paths";
  import {
    initializeTTS,
    speakText,
    stopTTS,
    pauseTTS,
    resumeTTS,
    isPaused,
  } from "$lib/audio";
  import { isDictationMode, autoScroll, isMuted } from "$lib/stores/audio";
  import { splitSentences } from "$lib/segmenter";
  import { updateDocumentProgress } from "$lib/database";
  import { videoSources } from "$lib/constants";
  import FeedSlide from "$lib/components/FeedSlide.svelte";
  import ReadingOptionsSheet from "$lib/components/ReadingOptionsSheet.svelte";
  import {
    ChevronLeft,
    MoreHorizontal,
    Volume2,
    VolumeX,
    ChevronUp,
  } from "lucide-svelte";
  // import Hammer from 'hammerjs'; // Removed static import to fix SSR error

  let {
    segments = [],
    initialIndex = 0,
    initialProgress = 0,
    documentId = "",
  } = $props();

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let swiperInstance: any = $state();
  let currentCharIndex: number = $state(-1);
  let highlightEndIndex: number | undefined = $state(undefined);
  let highlightStartIndex: number | undefined = $state(undefined);
  let activeIndex = $state(untrack(() => initialIndex));
  let currentSegmentProgress = 0;
  let isPlaying = $state(false);
  let isFirstPlay = true;
  let showOptions = $state(false);
  let boundaryCheckTimeout: ReturnType<typeof setTimeout>;
  let saveTimeout: ReturnType<typeof setTimeout>;

  function handleSwiperInit(e: CustomEvent) {
    const [swiper] = e.detail;
    swiperInstance = swiper;
    activeIndex = swiper.activeIndex;
    initializeTTS();
    if (segments.length > 0) {
      speakCurrentSlide();
    }
  }

  function handleSlideChange(e: CustomEvent) {
    if (segments.length > 0) {
      const [swiper] = e.detail;
      swiperInstance = swiper;
      // Save progress of previous slide (which is technically just saving the *fact* we moved, usually with 0 progress for new slide)
      // But we want to ensure we save the LAST known state before moving.
      // However, usually moving to next slide resets progress to 0 for that new slide.
      // So we save the NEW index and 0 progress.
      activeIndex = swiper.realIndex;
      currentSegmentProgress = 0; // Reset progress for new slide
      saveProgress(); // Persist the move (debounced by default)
      speakCurrentSlide();
    }
  }

  function saveProgress(immediate: boolean = false) {
    if (!documentId) return;

    if (saveTimeout) clearTimeout(saveTimeout);

    if (immediate) {
      updateDocumentProgress(documentId, activeIndex, currentSegmentProgress);
    } else {
      saveTimeout = setTimeout(() => {
        updateDocumentProgress(documentId, activeIndex, currentSegmentProgress);
      }, 1000);
    }
  }

  function speakCurrentSlide() {
    stopTTS(); // Stop any previous speech
    if (boundaryCheckTimeout) clearTimeout(boundaryCheckTimeout);
    currentCharIndex = -1;
    highlightEndIndex = undefined;
    highlightStartIndex = undefined;

    // Determine start index:
    // If it's the very first play and we are on the initial index, use initialProgress.
    // Otherwise, start from 0.
    let startIndex = 0;
    if (isFirstPlay && activeIndex === initialIndex) {
      startIndex = initialProgress;
      isFirstPlay = false;
    }

    currentSegmentProgress = startIndex;
    const currentSegment = segments[swiperInstance.realIndex];
    if (!currentSegment) return;

    if ($isDictationMode) {
      speakDictation(currentSegment, startIndex);
    } else {
      speakKaraoke(currentSegment, startIndex);
    }
  }

  function speakKaraoke(text: string, startIndex: number) {
    let boundaryFired = false;

    // Start checking for boundary events support
    boundaryCheckTimeout = setTimeout(() => {
      if (!boundaryFired && isPlaying) {
        console.warn("Boundary events missing, switching to Dictation Mode");
        stopTTS();
        isDictationMode.set(true);
        speakCurrentSlide(); // Restart in dictation mode
      }
    }, 1500);

    speakText(
      text,
      (_word, charIndex) => {
        boundaryFired = true;
        if (boundaryCheckTimeout) clearTimeout(boundaryCheckTimeout);
        currentCharIndex = charIndex;
        currentSegmentProgress = charIndex;
      },
      () => {
        if (boundaryCheckTimeout) clearTimeout(boundaryCheckTimeout);
        isPlaying = false;
        // When finished, set progress to the end of segment
        // This ensures granular progress reflects completion
        currentCharIndex = text.length;
        currentSegmentProgress = text.length;
        highlightEndIndex = undefined;
        highlightStartIndex = undefined;
        saveProgress(true); // Immediate save on completion

        if ($autoScroll && swiperInstance && !swiperInstance.isEnd) {
          swiperInstance.slideNext();
        }
      },
      startIndex,
    );
    isPlaying = true;
  }

  function speakDictation(text: string, startIndex: number) {
    const sentences = splitSentences(text);
    // Find sentences that haven't finished yet (end > startIndex)
    const sentenceQueue = sentences.filter((s) => s.end > startIndex);
    playNextSentence(sentenceQueue, startIndex);
  }

  function playNextSentence(
    queue: { text: string; start: number; end: number }[],
    originalStartIndex: number,
  ) {
    if (queue.length === 0) {
      isPlaying = false;
      // We assume completion of the segment
      currentCharIndex = segments[swiperInstance.realIndex].length;
      currentSegmentProgress = segments[swiperInstance.realIndex].length;
      highlightEndIndex = undefined;
      highlightStartIndex = undefined;
      saveProgress(true); // Immediate save on completion

      if ($autoScroll && swiperInstance && !swiperInstance.isEnd) {
        swiperInstance.slideNext();
      }
      return;
    }

    const currentSentence = queue[0];
    const remaining = queue.slice(1);

    // Update Highlight: highlight the whole sentence
    currentCharIndex = currentSentence.start;
    highlightEndIndex = currentSentence.end;
    highlightStartIndex = currentSentence.start;
    currentSegmentProgress = currentSentence.start;

    // Calculate offset if we are resuming mid-sentence
    // If originalStartIndex is within this sentence, start from there.
    // Else (for subsequent sentences, we don't have an offset
    const offset = Math.max(0, originalStartIndex - currentSentence.start);

    isPlaying = true;

    speakText(
      currentSentence.text,
      (_word, charIndex) => {
        // In dictation, charIndex is relative to the sentence.
        // We need absolute index in the segment.
        const absoluteIndex = currentSentence.start + charIndex;
        currentCharIndex = absoluteIndex;
        currentSegmentProgress = absoluteIndex;
      },
      () => {
        // On end of this sentence
        if (!isPlaying) return; // If stopped externally
        // For subsequent sentences, we don't have an offset
        playNextSentence(remaining, 0);
      },
      offset,
    );
  }

  function togglePlayback() {
    if (isPlaying) {
      pauseTTS();
      isPlaying = false;
      saveProgress(true); // Immediate save when paused
    } else {
      if (isPaused()) {
        resumeTTS();
      } else {
        // If not paused but not playing (e.g. finished), restart
        speakCurrentSlide();
      }
      isPlaying = true;
    }
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === " " || e.key === "Enter") {
      e.preventDefault();
      togglePlayback();
    }
  }

  onMount(async () => {
    register();
    initializeTTS();
  });

  onDestroy(() => {
    stopTTS();
    if (boundaryCheckTimeout) clearTimeout(boundaryCheckTimeout);
    if (saveTimeout) clearTimeout(saveTimeout);
    saveProgress(true); // Immediate save on exit
  });
</script>

<div class="w-full h-full relative bg-black">
  {#if segments.length > 0}
    <!-- Header -->
    <div
      class="absolute top-0 left-0 w-full z-40 p-4 flex items-center justify-between pointer-events-none"
    >
      <a
        href={resolve("/")}
        class="pointer-events-auto w-12 h-12 rounded-full flex items-center justify-center bg-[rgba(30,30,30,0.6)] backdrop-blur-md border border-white/15 hover:bg-white/20 transition duration-200"
      >
        <ChevronLeft class="text-white" size={24} />
      </a>

      <div
        class="px-4 py-2 rounded-full bg-[rgba(30,30,30,0.6)] backdrop-blur-md border border-white/15"
      >
        <span class="text-sm font-medium text-white/90"
          >Short {activeIndex + 1} / {segments.length}</span
        >
      </div>

      <button
        class="pointer-events-auto w-12 h-12 rounded-full flex items-center justify-center bg-[rgba(30,30,30,0.6)] backdrop-blur-md border border-white/15 hover:bg-white/20 transition duration-200"
        onclick={() => (showOptions = true)}
      >
        <MoreHorizontal class="text-white" size={24} />
      </button>
    </div>

    <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
    <!-- svelte-ignore a11y_no_noninteractive_tabindex -->
    <swiper-container
      direction="vertical"
      slides-per-view={1}
      space-between={0}
      mousewheel={true}
      initial-slide={initialIndex}
      class="mySwiper w-full h-full"
      data-testid="swiper-mock"
      onswiperinit={handleSwiperInit}
      onswiperslidechange={handleSlideChange}
      onclick={togglePlayback}
      role="region"
      aria-label="Video Feed"
      tabindex="0"
      onkeydown={handleKeydown}
    >
      {#each segments as segment, i (i)}
        <swiper-slide class="w-full h-full" data-testid="swiper-slide-mock">
          {#if Math.abs(i - activeIndex) <= 2}
            <FeedSlide
              {segment}
              isActive={i === activeIndex}
              {isPlaying}
              currentCharIndex={i === activeIndex ? currentCharIndex : -1}
              highlightEndIndex={i === activeIndex
                ? highlightEndIndex
                : undefined}
              highlightStartIndex={i === activeIndex
                ? highlightStartIndex
                : undefined}
              videoSource={videoSources[i % videoSources.length]}
            />
          {:else}
            <!-- Render placeholder for off-screen slides to save memory -->
            <div class="w-full h-full bg-black"></div>
          {/if}
        </swiper-slide>
      {/each}
    </swiper-container>
  {:else}
    <div class="flex flex-col items-center justify-center h-full text-white">
      <p class="text-xl">Upload a PDF to see the feed!</p>
    </div>
  {/if}

  <!-- Footer -->
  <div
    class="absolute bottom-0 left-0 w-full z-40 p-4 pointer-events-none flex flex-col items-center"
  >
    <!-- Mute Button (Left Aligned) -->
    <div class="w-full flex justify-start pb-4 pl-4">
      <button
        class="pointer-events-auto w-10 h-10 rounded-full flex items-center justify-center shadow-lg hover:brightness-110 transition duration-200 text-black bg-[#00ff88]"
        onclick={() => isMuted.update((v) => !v)}
      >
        {#if $isMuted}
          <VolumeX size={20} />
        {:else}
          <Volume2 size={20} />
        {/if}
      </button>
    </div>

    <!-- Swipe Indicator -->
    {#if activeIndex === 0}
      <div class="flex flex-col items-center animate-bounce space-y-1 mb-8">
        <ChevronUp class="text-[#00FF66]" size={32} strokeWidth={3} />
        <span
          class="text-xs font-medium text-white/90 tracking-wide uppercase shadow-black drop-shadow-sm"
          >Swipe up to continue</span
        >
      </div>
    {/if}
  </div>

  <!-- Options Sheet -->
  {#if showOptions}
    <ReadingOptionsSheet onClose={() => (showOptions = false)} />
  {/if}
</div>
